#!/usr/bin/ruby -w
# Cisco password 7 decrypter
# by CausticKirbyZ #

class String
  def as_hex
    "0x" + self.to_s
  end
end

def Crackpass(pass)
  constant = "tdf;kfoA,.iyewrkldJKD"
  index = (pass[0] + pass[1]).to_i - 1
  plain = ''
  puts (pass[0] + pass[1]).to_i
  i = 2

  while i < pass.length
    plain += ((pass[i] + pass[i + 1]).as_hex.to_i(16) ^ constant[index].ord).chr
    index += 1
    i += 2
  end

  return plain

end

def help()
  puts "
  Syntax: cisco7 <file.txt>
  "
end





#main logic
File.open(ARGV[0],'r') do |line|
  if line =~ /.*password 7.*/i 
    line.rpartition(' ')[2]





    enable password 7 1029384


    



